Move the navigation link into the outcome grid
5calls/ios pull request #414
Opened 2024-01-04 01:46 UTC by nickoneill

Looks like having a single nav link over a bunch of buttons was confusing VoiceOver. Making a nav link for each outcome button makes each button show in VoiceOver as expected.

Fixes #413

2024-01-04 14:50 UTC, cselin approved these changes
LGTM with one suggestion

2024-01-04 14:50 UTC, cselin commented on FiveCalls/FiveCalls/IssueContactDetail.swift
> +                    OutcomesView(outcomes: issue.outcomeModels, navModel: IssueDetailNavModel(issue: issue, contacts: nextContacts), report: { outcome in
nit: can we clean up some of the duplication here? seems like the only difference between the two is whether to include `nextContacts` or not and the nav model.

2024-01-04 20:44 UTC, heathermh requested changes
4 buttons are seen by VO, but I can't tap them to advance to next screen.

I've been working on an option for this on another branch where the buttons do advance, but report(outcome) in OutcomesView doesn't work yet. (this code isn't pushed to GitHub yet)

I'd like to see OutcomesView take a more specific data type for navModel. I have a suggestion in process for this part, too.

2024-01-04 20:51 UTC, heathermh commented
Also just saw that when testing on device but not using VO for an issue with two contacts, the first contact runs OK but then it doesn't go to next contact... just goes straight to done page.

2024-01-06 00:36 UTC, heathermh commented
> Also just saw that when testing on device but not using VO for an issue with two contacts, the first contact runs OK but then it doesn't go to next contact... just goes straight to done page.
> 
> Update: when I test for an issue with 3 contacts, the first 2 work fine and the last one is skipped.

Update: this is a bug in the state... when I added it on my other branch, it does this. It's not a VO problem. I'm going to PR my branch and add an issue for this.

2024-01-06 17:44 UTC, nickoneill commented
closing to fix in #420

2024-01-06 17:44 UTC, closed without merging